# send_email.py

import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage

def send_email(image_path):
    password = 'tkel szui qieu fnin'
    receiver = 'deseseese@gmail.com'
    sender = 'deseseese@gmail.com'
    msg = MIMEMultipart()
    msg['To'] = receiver
    msg['From'] = 'Security Alert: Unidentified Person Detected <' + sender + '>'
    msg['Subject'] = 'Urgent: Security Alert - Unidentified Individual Detected on Camera'

    msg_body = """\
    Dear [Recipient's Name],

    This message is generated by our automated door camera system.

    We regret to inform you that an unidentified individual has been detected by our surveillance system. Attached to this email is an image captured by our automated door camera.

    The safety and security of our premises are of utmost importance to us, and we wanted to promptly bring this matter to your attention.

    Please review the attached image at your earliest convenience. If you recognize the individual or if you have any concerns, please do not hesitate to contact us.

    Thank you for your cooperation in maintaining the security of our facility.

    Best regards,
    [Your Name]
    Automated Door Camera System
    [Your Contact Information]
    """

    msg_ready = MIMEText(msg_body, 'plain')

    # Attach image
    with open(image_path, 'rb') as fp:
        image_ready = MIMEImage(fp.read())
        image_ready.add_header('Content-Disposition', 'attachment', filename=os.path.basename(image_path))
        msg.attach(image_ready)

    # Establishing connection with Gmail SMTP server
    context_data = ssl.create_default_context()

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context_data) as server:
        server.login(sender, password)
        server.send_message(msg)

    print("Email sent")
